# Generated by Django 4.0.4 on 2023-09-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('branch', models.CharField(max_length=32)),
                ('generation', models.CharField(max_length=32)),
                ('debut_date', models.DateField()),
                ('tagline', models.TextField(max_length=96)),
            ],
        ),
        migrations.DeleteModel(
            name='Weapons',
        ),
    ]
